config/routes.rb
Rails.application.routes.draw do

  root to: 'wiki#index', as: 'root'

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  resources :wiki

  get '/home' => 'home#index'

  controller :sessions do
    get 'login'  => :new
    post 'login'  => :create
    delete 'logout' => :destroy
  end
end

app/models/role/admin.rb
module Role
  class Admin < Base
    def can?(_controller, _action)
      true
    end
  end
end

app/models/role/base.rb
module Role
  class Base < User
    attr_accessor :permissions

    def self.model_name
      ActiveModel::Name.new(User)
    end

    def can?(controller, action)
      @controller, @action = controller.to_sym, action.to_sym

      can_do?
    end

    private

    def can_do?
      actions = permissions.try :[], @controller

      return false if actions.blank?
      return true  if actions == :all

      @action.in? actions
    end
  end
end

app/models/role/guest.rb
module Role
  class Guest < Base
    private def permissions
      {
        home: [:index],
        sessions: [:new, :create],
        wiki: [:index, :show]
      }
    end
  end
end

app/models/role/manager.rb
module Role
  class Manager < Base
    private def permissions
      {
        home: :all,
        images: :all,
        image_galleries: :all,
        bootsy: :all,
        sessions: :all
      }
    end
  end
end

app/models/seo_metadata.rb
class SeoMetadata < ActiveRecord::Base
  belongs_to :wiki

  validates :keywords, :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  self.inheritance_column = 'role'

  enum role: {
    admin:   'Role::Admin',
    manager: 'Role::Manager',
    guest:   'Role::Guest'
  }

  has_secure_password

  validates :name, :role, presence: true
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  include Bootsy::Container
  has_one :seo_metadata, dependent: :delete
  accepts_nested_attributes_for :seo_metadata, allow_destroy: true

  validates_associated :seo_metadata
  validates :title, :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  before_action :authorize

  protect_from_forgery with: :exception

  protected

  def authorize
    return if current_user.can?(params[:controller], params[:action])
    redirect_to root_url, notice: 'You no have permissions to do this.'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # GET /
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # GET /login
  def new
  end

  # POST /login
  def create
    if sessions_is_authenticated?
      redirect_to root_url
    else
      redirect_to login_url, alert: 'Invalid user/password combination'
    end
  end

  # DELETE /logout
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out'
  end

  private

  def sessions_is_authenticated?
    user = User.find_by(name: params[:login])
    return false unless user && user.authenticate(params[:password])
    session[:user_id] = user.id
  end
end

app/controllers/wiki_controller.rb
class WikiController < ApplicationController
  before_action :set_wiki, only: %i(show edit update destroy)

  # GET /wiki
  def index
    @wiki = Wiki.all
  end

  # GET /wiki/1
  def show
  end

  # GET /wiki/new
  def new
    @wiki = Wiki.new seo_metadata: SeoMetadata.new
  end

  # GET /wiki/1/edit
  def edit
  end

  # POST /wiki
  def create
    @wiki = Wiki.new(wiki_params)

    if params[:preview_button]
      render :new
    elsif params[:commit]
      if @wiki.save
        redirect_to @wiki, notice: 'Wiki was successfully created.'
      else
        render :new
      end
    end
  end

  # PATCH/PUT /wiki/1
  def update
    if params[:preview_button]
      render :new
    elsif params[:commit]
      if @wiki.update(wiki_params)
        redirect_to @wiki, notice: 'Wiki was successfully updated.'
      else
        render :edit
      end
    end
  end

  # DELETE /wiki/1
  def destroy
    @wiki.destroy
    redirect_to wiki_index_url, notice: 'Wiki was successfully destroyed.'
  end

  private

  def set_wiki
    @wiki = Wiki.find(params[:id])
  end

  def wiki_params
    params.require(:wiki).permit(
      :title,
      :text,
      :bootsy_image_gallery_id,
      seo_metadata_attributes: [:keywords, :description])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    return Role::Guest.new unless session[:user_id]
    @_current_user ||= User.find(session[:user_id])
  end
end

app/views/application/_footer.html.haml
%footer
  = render 'application/counters/yandex' # if Rails.env.production?

app/views/application/_header.html.haml
%header
  %nav.navbar.navbar-default
    .navbar-header
      = link_to 'AzartWiki', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      - if current_user.admin?
        %p.navbar-text.navbar-right.navbar-link
          = link_to t('sign_out'), logout_url, method: :delete

app/views/application/_meta_data.html.haml
= tag 'meta', name: 'Keywords',    content: (content_for(:meta_keywords)    || t('.default_meta_keywords')   )
= tag 'meta', name: 'Description', content: (content_for(:meta_description) || t('.default_meta_description'))
%meta{ content: 'text/html; charset=utf-8', 'http-equiv' => 'Content-Type' }
%meta{ name: 'robots',    content: 'all' }
%meta{ name: 'googlebot', content: 'all' }
= render 'application/shim'

app/views/application/_shim.html.haml
/[if lt IE 9]
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>

app/views/application/counters/_google.html.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-12238425-3', 'auto');
  ga('send', 'pageview');

app/views/application/counters/_yandex.html.erb
<!-- Yandex.Metrika informer -->
<!-- <a href="https://metrika.yandex.ru/stat/?id=26331555&amp;from=informer"
target="_blank" rel="nofollow" style"display:none"><img src="//bs.yandex.ru/informer/26331555/1_0_FFFFFFFF_FFFFFFFF_0_pageviews"
style="width:80px; height:15px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры)" onclick="try{Ya.Metrika.informer({i:this,id:26331555,lang:'ru'});return false}catch(e){}"/></a> -->
<!-- /Yandex.Metrika informer -->

<!-- Yandex.Metrika counter -->
<script type="text/javascript">
(function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter26331555 = new Ya.Metrika({id:26331555,
                    webvisor:true,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true});
        } catch(e) { }
    });

    var n = d.getElementsByTagName("script")[0],
        s = d.createElement("script"),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = "text/javascript";
    s.async = true;
    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

    if (w.opera == "[object Opera]") {
        d.addEventListener("DOMContentLoaded", f, false);
    } else { f(); }
})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/26331555" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

app/views/application/counters/_yandex.html.haml
/ Yandex.Metrika counter
:javascript
  (function (d, w, c) {
      (w[c] = w[c] || []).push(function() {
          try {
              w.yaCounter26331555 = new Ya.Metrika({id:26331555,
                      webvisor:true,
                      clickmap:true,
                      trackLinks:true,
                      accurateTrackBounce:true});
          } catch(e) { }
      });

      var n = d.getElementsByTagName("script")[0],
          s = d.createElement("script"),
          f = function () { n.parentNode.insertBefore(s, n); };
      s.type = "text/javascript";
      s.async = true;
      s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

      if (w.opera == "[object Opera]") {
          d.addEventListener("DOMContentLoaded", f, false);
      } else { f(); }
  })(document, window, "yandex_metrika_callbacks");
%noscript
  %div
    %img{alt: '', src: '//mc.yandex.ru/watch/26331555', style: 'position:absolute; left:-9999px;'}/
/ /Yandex.Metrika counter

app/views/application/counters/_yandex_view.html.erb
<!-- Yandex.Metrika informer -->
<a href="https://metrika.yandex.ru/stat/?id=26331555&amp;from=informer"
target="_blank" rel="nofollow" style"display:none"><img src="//bs.yandex.ru/informer/26331555/1_0_FFFFFFFF_FFFFFFFF_0_pageviews"
style="width:80px; height:15px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры)" onclick="try{Ya.Metrika.informer({i:this,id:26331555,lang:'ru'});return false}catch(e){}"/></a>
<!-- /Yandex.Metrika informer -->

app/views/home/index.html.haml
#coming-soon
  %h1 Azartwiki.com is coming soon.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= content_for(:page_title) || t('.default_page_title')
    = favicon_link_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolink-track'  => true,      async: true
    = javascript_include_tag 'application',               'data-turbolinks-track' => true,      async: true
    = csrf_meta_tags
    = render 'application/meta_data'
  %body
    = render 'application/counters/google' if Rails.env.production?
    = render 'application/counters/yandex' if Rails.env.production?

    = render 'application/header'

    - flash.each do |key, value|
      = content_tag :p, value, id: key, class: 'alert'

    .container

      = yield

    = render 'application/footer'

app/views/wiki/_form.html.haml
= simple_form_for @wiki, class: 'form-horizontal' do |f|
  = f.error_notification

  - if params[:preview_button]
    .panel.panel-default
      .panel-heading
        %h3
          = @wiki.title
      .panel-body
        = raw @wiki.text

  .form-controls
    = f.simple_fields_for :seo_metadata do |seo_form|
      = seo_form.input :keywords
      = seo_form.input :description
    = f.input :title
    = f.input :text, as: :bootsy, input_html: {style: 'width: 650px; height: 300px;'}

  .form-actions
    = f.button :submit, 'Submit'
    = f.button :submit, 'Preview', name: :preview_button

app/views/wiki/edit.html.haml
.panel.panel-default
  .panel-heading
    %h3 Editing wiki
  
  .panel-body
    = raw render 'form'

  .panel-footer
    = link_to 'Show', @wiki, class: 'btn btn-info'
    = link_to 'Back', wiki_index_path, class: 'btn btn-danger'

app/views/wiki/index.html.haml
- provide :page_title,       t('.page_title')
- provide :meta_keywords,    t('.meta_keywords')
- provide :meta_description, t('.meta_description')
.row
  .panel.panel-default
    .panel-heading
      %h3 Listing wiki
    .panel-body
      %table.table.table-striped.table-bordered.table-hover
        %tr
          %th Title
          %th Created at
          - if current_user.admin?
            %th Actions

        - @wiki.each do |wiki|
          %tr
            %td= link_to wiki.title, wiki
            %td= wiki.created_at.to_date
            - if current_user.admin?
              %td
                = link_to 'Show', wiki, class: 'btn btn-default'
                = link_to 'Edit', edit_wiki_path(wiki), class: 'btn btn-info'
                = link_to 'Destroy', wiki, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

      %br
    .panel-footer
      - if current_user.admin?
        = link_to 'Create new Wiki', new_wiki_path, class: 'btn btn-default'

app/views/wiki/new.html.haml
.panel.panel-default
  .panel-heading
    %h3 New wiki
  .panel-body

    = render 'form'
  .panel-footer
    = link_to 'Back', wiki_index_path, class: 'btn btn-danger'

app/views/wiki/show.html.haml
- provide :page_title,       t('.page_title',       title:       @wiki.title)
- provide :meta_keywords,    t('.meta_keywords',    keywords:    @wiki.seo_metadata.keywords)
- provide :meta_description, t('.meta_description', description: @wiki.seo_metadata.description)

.panel.panel-default
  .panel-heading
    %h3
      = @wiki.title
  .panel-body
    = raw @wiki.text
  .panel-footer
    - if current_user.admin?
      = link_to 'Edit', edit_wiki_path(@wiki), class: 'btn btn-info'
      = link_to 'Back', wiki_index_path, class: 'btn btn-danger'